import { db } from './src/lib/db'

async function seed() {
  // First, delete all existing artworks to do a clean re-seed
  await db.purchaseInquiry.deleteMany()
  await db.artwork.deleteMany()
  console.log('Cleared existing artworks and inquiries.')

  const artworks = [
    {
      id: 'interpreted-space',
      title: "Interpreted Space",
      description: "This painting is a journey to distant horizons. Are they real, are they imaginary? Sometimes our dreams mingle with reality, our darkness mingles with the light. Who knows if there is a border? A French collector commented: \"Ce tableau est un voyage vers des horizons lointains.\"",
      price: 2800,
      medium: "Oil on canvas",
      dimensions: '16 x 20 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/29024f7e-824c-4445-a7f0-4117e2cdb127/image_123650291.JPG?format=1500w",
      isAvailable: true,
      sortOrder: 1,
    },
    {
      id: 'pink-panther-and-the-pig-headed-boy',
      title: "Pink Panther And The Pig Headed Boy",
      description: "A striking 2011 oil painting that merges pop culture imagery with raw expressionistic brushwork. The playful yet confrontational title hints at the layered contradictions within the work, where childhood nostalgia collides with adult complexity.",
      price: 3200,
      medium: "Oil on canvas",
      dimensions: '20 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/e5377294-5d11-4a89-8886-18d58b3d6eed/DSCF9606-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 2,
    },
    {
      id: 'nijinsky',
      title: "Nijinsky",
      description: "A collector noted: \"Carter's captivating art piece exudes gold and yellow tones accentuated by subtle grey hues. The red eyes peering from the center surrounded by dripping paint evoke a sense of mystery and intrigue. The combination of color tones draw you in to the finer detail in the painting that makes me stare at it longer and longer.\"",
      price: 4800,
      medium: "Oil on canvas",
      dimensions: '36 x 48 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/5a173ec1-40a7-46c0-bab5-a1c74b7a2982/Nijinsky.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 3,
    },
    {
      id: 'portrait-of-art-instructor-ai',
      title: "Portrait Of Art Instructor Ai",
      description: "A 2023 portrait rendered in a blend of acrylic and oil on canvas, capturing the essence of an art instructor with Carter's signature abstract sensibility. The piece bridges the gap between figurative representation and expressive abstraction.",
      price: 2400,
      medium: "Acrylic and oil on canvas",
      dimensions: '18 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/cbb798ed-db63-4a98-b9b9-dfed4a71b8ad/DSCF9605-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 4,
    },
    {
      id: 'nine-eleven',
      title: "911",
      description: "A powerful 2011 work responding to the September 11 attacks. Measuring 30 by 40 inches, this oil on canvas confronts the trauma and collective memory of that day through Carter's abstract visual language, channeling grief and resilience into every layer of paint.",
      price: 5200,
      medium: "Oil on canvas",
      dimensions: '30 x 40 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/1705371643201-QEGBN5W2KVZIN56RHVDB/DSCF9645-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 5,
    },
    {
      id: 'casey',
      title: "Casey",
      description: "An intimate 2015 oil portrait on canvas. The 18 by 24 inch format creates a personal connection between subject and viewer, rendered with the emotional depth and empathetic gaze that defines Carter's approach to portraiture.",
      price: 2200,
      medium: "Oil on canvas",
      dimensions: '18 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/76b00847-1b35-40c4-964a-b1dce74334d0/DSCF9629-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 6,
    },
    {
      id: 'throat-nyc',
      title: "Throat NYC",
      description: "A 2012 oil on canvas work that captures the visceral energy of New York City. At 16 by 20 inches, this compact painting packs an intense emotional punch, reflecting the raw pulse of downtown Manhattan through Carter's distinctive abstract lens.",
      price: 2000,
      medium: "Oil on canvas",
      dimensions: '16 x 20 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/d57150b2-00dd-41d7-8e1d-fa39a98ffd3c/DSCF9618-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 7,
    },
    {
      id: 'choices',
      title: "Choices",
      description: "A 2022 work combining acrylic and oil on canvas. This 18 by 24 inch painting explores the complexity of decision-making through intersecting forms and contrasting colors, each brushstroke representing a path taken or a possibility left behind.",
      price: 2600,
      medium: "Acrylic and oil on canvas",
      dimensions: '18 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/e09724cf-851c-44da-830f-44f559ec568b/DSCF9602-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 8,
    },
    {
      id: 'bakery',
      title: "Bakery",
      description: "A charming 2023 oil on canvas capturing the warmth and texture of a neighborhood bakery. This compact 10 by 10 inch piece demonstrates Carter's ability to find beauty in everyday scenes, transforming the ordinary into something extraordinary through bold color and confident brushwork.",
      price: 1200,
      medium: "Oil on canvas",
      dimensions: '10 x 10 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/832b7166-5358-401e-9ccb-ea4c314a53fc/Bakery+10x10+inches+Oil+on+canvas+2023.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 9,
    },
    {
      id: 'hibakusha-nuclear-riki',
      title: "Hibakusha Nuclear Riki",
      description: "91-year-old Riki Takashima shared her experience of being in Japan when nuclear bombs were detonated. This face describes the horror she shared. A powerful 2023 acrylic on canvas that bears witness to one of history's darkest moments through the deeply personal lens of a survivor's story.",
      price: 2800,
      medium: "Acrylic on canvas",
      dimensions: '18 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/078623e1-e050-40d2-a865-5e9053675191/Riki+pointing+to+her+painting+entitled+Habakusha+Nuclear+Riki.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 10,
    },
    {
      id: 'death-in-ukraine',
      title: "Death In Ukraine",
      description: "A harrowing 2023 oil on canvas responding to the war in Ukraine. At 30 by 40 inches, this large-scale work confronts the viewer with the human cost of conflict, channeling Carter's deep empathy for humanity into a visual indictment of violence and suffering.",
      price: 5200,
      medium: "Oil on canvas",
      dimensions: '30 x 40 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/b5c14bf5-14b6-413a-bc55-5576457d7cb4/DSCF9613-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 11,
    },
    {
      id: 'abjection',
      title: "Abjection",
      description: "A bold 2011 oil on canvas measuring 36 by 24 inches. This work explores themes of rejection and marginalization through raw, expressive forms. The horizontal format creates a panoramic emotional landscape that draws the viewer into its challenging narrative.",
      price: 4200,
      medium: "Oil on canvas",
      dimensions: '36 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/1705370257958-12Y7CAQZDPDB7CX2HIC1/DSCF9624-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 12,
    },
    {
      id: 'orientation-new-york',
      title: "Orientation New York",
      description: "A 2022 oil on canvas that captures the disorienting energy of New York City. At 18 by 24 inches, this painting maps the emotional geography of the city through abstract forms, reflecting how the urban landscape shapes and distorts our sense of direction and belonging.",
      price: 2600,
      medium: "Oil on canvas",
      dimensions: '18 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/1709611337438-X13B2WAXNPE849M60FHN/DSCF9617-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 13,
    },
    {
      id: 'equation',
      title: "Equation",
      description: "A 2023 oil on canvas where Carter's background in diagnostic imaging meets artistic expression. Measuring 27 by 24 inches, this work balances analytical precision with creative intuition, suggesting that art and science are simply two languages describing the same truth.",
      price: 3000,
      medium: "Oil on canvas",
      dimensions: '27 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/d930cf16-646e-4d19-a013-839052bcd69b/DSCF9599-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 14,
    },
    {
      id: 'loop',
      title: "Loop",
      description: "An extraordinary 8 by 50 inch oil on plywood from 2015, currently owned by violinist Sooyeon Jun. This panoramic work stretches across an elongated format, creating a continuous visual narrative that flows like music — a fitting home for a musician's collection.",
      price: 8500,
      medium: "Oil on plywood",
      dimensions: '8 x 50 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/06975533-5b72-4cb4-a052-d58ec5af000a/Loop+8x50+inches+oil+on+plywood+2015+owned+by+Sooyeon+Jun.jpg?format=1500w",
      isAvailable: false,
      sortOrder: 15,
    },
    {
      id: 'neighbors',
      title: "Neighbors",
      description: "A watercolor on paper measuring 26 by 38 inches. This larger work in watercolor demonstrates Carter's versatility across media, using the fluid transparency of watercolor to explore the interconnectedness of community and the quiet drama of proximity.",
      price: 3400,
      medium: "Watercolor on paper",
      dimensions: '26 x 38 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/1755725034639-W9MXXC5R70FIW7CJQZ61/Neighbors.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 16,
    },
    {
      id: 'cheburashka',
      title: "Cheburashka",
      description: "A 16 by 20 inch oil on canvas inspired by the beloved Russian literary character. Carter reimagines this cultural icon through his abstract lens, blending whimsy with deeper themes of displacement, belonging, and the universal desire for connection.",
      price: 1800,
      medium: "Oil on canvas",
      dimensions: '16 x 20 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/7e56260f-d76d-4926-94fc-7832d3f3e248/Cheburashka.png?format=1500w",
      isAvailable: true,
      sortOrder: 17,
    },
    {
      id: 'conductor',
      title: "Conductor",
      description: "A compact 12 by 16 inch oil on canvas that captures the kinetic energy of a musical conductor. The tight format concentrates the emotional intensity of performance, with sweeping brushstrokes mimicking the arc of a baton cutting through silence.",
      price: 1400,
      medium: "Oil on canvas",
      dimensions: '12 x 16 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/6e17e629-eb1c-48fd-a951-6d6686219cc3/Conductor.png?format=1500w",
      isAvailable: true,
      sortOrder: 18,
    },
    {
      id: 'model',
      title: "Model",
      description: "An 18 by 24 inch acrylic on paper exploring the relationship between artist and subject. This work deconstructs the traditional figure study, abstracting the human form into essential gestures and emotional residues that linger long after the sitting has ended.",
      price: 1600,
      medium: "Acrylic on paper",
      dimensions: '18 x 24 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/6b7da51a-dc2e-4646-a965-0e20dfbc1183/Model.png?format=1500w",
      isAvailable: true,
      sortOrder: 19,
    },
    {
      id: 'post-truth',
      title: "Post-Truth",
      description: "A commanding 40 by 40 inch oil on canvas that confronts the erosion of shared reality in the modern era. The square format creates a balanced tension between order and chaos, reflecting the disorienting landscape of misinformation and fractured narratives.",
      price: 5600,
      medium: "Oil on canvas",
      dimensions: '40 x 40 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/f4a96449-5761-4d7e-aa65-150f9607fb66/POST+TRUTH.png?format=1500w",
      isAvailable: true,
      sortOrder: 20,
    },
    {
      id: 'sycophant',
      title: "Sycophant",
      description: "A 22 by 30 inch watercolor on paper that critiques the culture of flattery and self-serving compliance. Watercolor's inherent unpredictability serves the theme perfectly, with bleeding edges and translucent layers suggesting the erosion of authenticity under social pressure.",
      price: 2200,
      medium: "Watercolor on paper",
      dimensions: '22 x 30 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/ca28dfdc-4797-44c3-8316-f066749acd03/Sycophant.png?format=1500w",
      isAvailable: true,
      sortOrder: 21,
    },
    {
      id: 'tic-tok',
      title: "Tic Tok",
      description: "A 16 by 20 inch acrylic on canvas that riffs on the relentless pace of digital culture. The title's deliberate misspelling echoes the disruptive nature of social media, while the painting's layered surfaces suggest the addictive scrolling of contemporary attention.",
      price: 1800,
      medium: "Acrylic on canvas",
      dimensions: '16 x 20 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/77c83cf5-a7cf-4463-a65f-9b3c4f11d872/Tic+Tok.png?format=1500w",
      isAvailable: true,
      sortOrder: 22,
    },
    {
      id: 'trudy2',
      title: "Trudy2",
      description: "A 16 by 20 inch oil on canvas portrait, the second in a series exploring a single subject through Carter's evolving abstract language. The compact format demands intimate engagement, rewarding close looking with layers of emotional and visual complexity.",
      price: 1800,
      medium: "Oil on canvas",
      dimensions: '16 x 20 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/de27c307-ab13-464d-903f-4a91efcc34dc/Trudy1.png?format=1500w",
      isAvailable: true,
      sortOrder: 23,
    },
    {
      id: 'war',
      title: "War",
      description: "A 16 by 20 inch acrylic on canvas that distills the chaos and destruction of armed conflict into its rawest visual elements. Despite its compact size, this painting carries an enormous emotional weight, bearing witness to the universal tragedy of violence.",
      price: 1800,
      medium: "Acrylic on canvas",
      dimensions: '16 x 20 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/80390f3a-a074-4da4-b84a-76dc4dff5904/War.png?format=1500w",
      isAvailable: true,
      sortOrder: 24,
    },
    {
      id: 'white-boy',
      title: "White boy",
      description: "A 16 by 20 inch oil on canvas that explores identity and perception through Carter's abstract expressionist approach. The title's provocative simplicity opens a dialogue about race, visibility, and the stories we tell about ourselves and each other.",
      price: 1800,
      medium: "Oil on canvas",
      dimensions: '16 x 20 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/1705370545557-CZ0LHBIBAXQD95UEIWBR/DSCF9625-Enhanced-NR.jpg?format=1500w",
      isAvailable: true,
      sortOrder: 25,
    },
    {
      id: 'jean-alian',
      title: "Jean-Alian",
      description: "A 16 by 20 inch pastel on canvas demonstrating Carter's command of yet another medium. The soft, velvety quality of pastel creates a dreamlike atmosphere, rendering the subject with a tenderness that feels both deeply personal and universally relatable.",
      price: 1800,
      medium: "Pastel on canvas",
      dimensions: '16 x 20 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/d745f8ad-78e5-4215-8d23-2f662528216f/Jean_Alian.png?format=1500w",
      isAvailable: true,
      sortOrder: 26,
    },
    {
      id: 'nosy-baboon',
      title: "Nosy Baboon",
      description: "A 24 by 36 inch watercolor on paper that brings a primal, almost mischievous energy to the gallery. The larger watercolor format allows for expansive washes of color that give the subject an atmospheric presence, as if caught in its natural habitat rather than confined to paper.",
      price: 2800,
      medium: "Watercolor on paper",
      dimensions: '24 x 36 in',
      imageUrl: "https://images.squarespace-cdn.com/content/v1/6598bd928a7fcc2ab5804a23/2a65df4c-76ba-4a9d-b5d3-0b824bfac036/tempImageTkCn9y.png?format=1500w",
      isAvailable: true,
      sortOrder: 27,
    },
  ]

  console.log('Seeding artworks...')
  for (const artwork of artworks) {
    const created = await db.artwork.upsert({
      where: { id: artwork.id },
      update: artwork,
      create: artwork,
    })
    console.log(`  ${created.isAvailable ? '✓' : '✗ SOLD'} ${created.title} — ${created.medium}, ${created.dimensions}`)
  }
  console.log(`\nDone! Seeded ${artworks.length} artworks (${artworks.filter(a => a.isAvailable).length} available, ${artworks.filter(a => !a.isAvailable).length} sold).`)
}

seed()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => {
    void db.$disconnect()
  })